# Generated by Django 4.2.1 on 2023-09-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tantou',
            field=models.CharField(blank=True, max_length=10, verbose_name='担当'),
        ),
    ]
