# Generated by Django 4.2.1 on 2023-09-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_tantou'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='com',
            field=models.CharField(blank=True, max_length=255, verbose_name='会社名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='氏名'),
        ),
    ]
