# Generated by Django 4.2.1 on 2023-09-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_busho_id_customer_mw_busho_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grip',
        ),
    ]
