# Generated by Django 4.2.1 on 2024-05-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_customer_royal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tel_mob_serch',
            new_name='tel_mob_search',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tel_serch',
            new_name='tel_search',
        ),
    ]
