# Generated by Django 4.2.1 on 2024-05-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_tel_mob_serch_customer_tel_mob_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_action',
            name='approach_id',
            field=models.IntegerField(default=0, verbose_name='アプローチID'),
        ),
    ]
