# Generated by Django 4.2.1 on 2025-08-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houjin_gaisho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieve_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='受信日時')),
                ('kubun', models.CharField(blank=True, max_length=255, null=True, verbose_name='区分')),
                ('houjin_com', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_会社')),
                ('houjin_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_部署')),
                ('houjin_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_電話番号')),
                ('houjin_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_メールアドレス')),
                ('houjin_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_住所')),
                ('houjin_tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_担当')),
                ('houjin_comment', models.TextField(blank=True, null=True, verbose_name='法人_コメント')),
            ],
        ),
    ]
