# Generated by Django 4.2.1 on 2025-08-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houjin_gaisho',
            name='houjin_comment2',
            field=models.TextField(blank=True, null=True, verbose_name='法人_コメント'),
        ),
    ]
