# Generated by Django 4.2.1 on 2025-08-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0002_houjin_gaisho_houjin_comment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houjin_gaisho',
            name='houjin_comment2',
        ),
    ]
