# Generated by Django 4.2.1 on 2025-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0003_remove_houjin_gaisho_houjin_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houjin_gaishou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieve_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='受信日時')),
                ('kubun', models.CharField(blank=True, max_length=255, null=True, verbose_name='区分')),
                ('houjin_com', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_会社')),
                ('houjin_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_部署')),
                ('houjin_tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_担当')),
                ('houjin_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_電話番号')),
                ('houjin_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_メールアドレス')),
                ('houjin_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人_住所')),
                ('houjin_comment', models.TextField(blank=True, null=True, verbose_name='法人_コメント')),
                ('boad_col', models.CharField(default=0, max_length=255, verbose_name='ボード_列')),
                ('boad_row', models.IntegerField(default=0, verbose_name='ボード_行')),
                ('tantou_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当ID')),
                ('tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者')),
                ('bikou', models.TextField(blank=True, null=True, verbose_name='P1備考')),
                ('itaku_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='委託会社_内容')),
                ('itaku_bikou', models.TextField(blank=True, null=True, verbose_name='委託会社_備考')),
            ],
        ),
        migrations.DeleteModel(
            name='Houjin_gaisho',
        ),
    ]
