# Generated by Django 4.2.1 on 2025-08-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0004_houjin_gaishou_delete_houjin_gaisho'),
    ]

    operations = [
        migrations.AddField(
            model_name='houjin_gaishou',
            name='last_update',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新日'),
        ),
    ]
