# Generated by Django 4.2.1 on 2025-08-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0006_alter_houjin_gaishou_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houjin_gaishou',
            name='last_update',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新日'),
        ),
    ]
