# Generated by Django 4.2.1 on 2025-08-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0007_alter_houjin_gaishou_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houjin_gaishou',
            name='tantou_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='担当ID'),
        ),
    ]
