# Generated by Django 4.2.1 on 2025-09-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0008_alter_houjin_gaishou_tantou_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houjin_gaishou',
            name='last_update',
        ),
        migrations.AddField(
            model_name='houjin_gaishou',
            name='imp_type',
            field=models.IntegerField(default=0, verbose_name='取込タイプ'),
        ),
        migrations.AddField(
            model_name='houjin_gaishou',
            name='last_act',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終アクション日'),
        ),
    ]
