# Generated by Django 4.2.1 on 2025-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0009_remove_houjin_gaishou_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houjin_gaishou',
            name='busho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='houjin_gaishou',
            name='busho_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部署ID'),
        ),
    ]
