# Generated by Django 4.2.1 on 2025-09-03 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0010_houjin_gaishou_busho_houjin_gaishou_busho_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='houjin_gaishou',
            name='imp_day',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='取込日時'),
            preserve_default=False,
        ),
    ]
