# Generated by Django 4.2.1 on 2025-09-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0011_houjin_gaishou_imp_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houjin_gaishou',
            name='imp_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='取込日時'),
        ),
    ]
