# Generated by Django 4.2.1 on 2026-02-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0012_alter_houjin_gaishou_imp_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houjin_gaishou',
            name='itaku_bikou',
        ),
    ]
