# Generated by Django 4.2.1 on 2026-06-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houjin', '0013_remove_houjin_gaishou_itaku_bikou'),
    ]

    operations = [
        migrations.AddField(
            model_name='houjin_gaishou',
            name='next_act',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='次回アクション日'),
        ),
    ]
