# Generated by Django 4.2.1 on 2023-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='test',
            field=models.CharField(default=1, max_length=10, verbose_name='test'),
            preserve_default=False,
        ),
    ]
