# Generated by Django 4.2.1 on 2023-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0003_remove_sfa_data_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='mw',
            field=models.IntegerField(default=0, verbose_name='メールワイズ'),
        ),
    ]
