# Generated by Django 4.2.1 on 2023-08-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0004_sfa_data_mw'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='busho_id',
            field=models.CharField(default=1, max_length=5, verbose_name='部署ID'),
            preserve_default=False,
        ),
    ]
