# Generated by Django 4.2.1 on 2023-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0006_member_last_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='com_busho',
            field=models.CharField(blank=True, max_length=50, verbose_name='部課名'),
        ),
    ]
