# Generated by Django 4.2.1 on 2023-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0007_sfa_data_com_busho'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='make_day',
            field=models.CharField(default=1, max_length=10, verbose_name='見積作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='mitsu_url',
            field=models.CharField(default=1, max_length=100, verbose_name='見積URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='update_day',
            field=models.CharField(default=1, max_length=20, verbose_name='更新日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='mitsu_day',
            field=models.CharField(blank=True, max_length=10, verbose_name='初回見積日'),
        ),
    ]
