# Generated by Django 4.2.1 on 2023-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0008_sfa_data_make_day_sfa_data_mitsu_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_data',
            name='busho_id',
            field=models.CharField(max_length=5, verbose_name='部署ID'),
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='make_day',
            field=models.CharField(blank=True, max_length=10, verbose_name='見積作成日'),
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='mitsu_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='見積URL'),
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='tantou_id',
            field=models.CharField(max_length=5, verbose_name='担当ID'),
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='update_day',
            field=models.CharField(blank=True, max_length=20, verbose_name='更新日'),
        ),
    ]
