# Generated by Django 4.2.1 on 2023-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0010_alter_member_last_api_alter_sfa_data_busho_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='kakudo_day',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='予想年月'),
        ),
    ]
