# Generated by Django 4.2.1 on 2023-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0014_sfa_action_cus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='hidden_day',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='非表示日時'),
        ),
    ]
