# Generated by Django 4.2.1 on 2026-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_est',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='問合せ_ID')),
                ('web_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='問合せ_受付番号')),
                ('web_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='問合せ_日時')),
                ('cus_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客_ID')),
                ('cus_sei', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客_姓')),
                ('cus_mei', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客_名')),
                ('pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客_都道府県')),
                ('web_kazu', models.IntegerField(default=0, verbose_name='問合せ_枚数')),
                ('mitsu_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='見積_ID')),
                ('mitsu_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='見積_見積番号')),
                ('mitsu_ver', models.CharField(blank=True, max_length=255, null=True, verbose_name='見積_バージョン')),
                ('kubun', models.CharField(blank=True, max_length=255, null=True, verbose_name='注文区分')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス')),
                ('juchu_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='受注日')),
                ('mitsu_kazu', models.IntegerField(default=0, verbose_name='見積_枚数')),
                ('money', models.IntegerField(default=0, verbose_name='見積金額')),
                ('busho_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='部署_ID')),
                ('busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='部署名')),
                ('tantou_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当_ID')),
                ('tantou_sei', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当_姓')),
                ('tantou_mei', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当_名')),
            ],
        ),
    ]
