# Generated by Django 4.2.1 on 2023-07-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsu_id', models.CharField(max_length=10, verbose_name='見積番号')),
                ('mitsu_ver', models.CharField(max_length=10, verbose_name='見積バージョン')),
                ('status', models.CharField(max_length=10, verbose_name='ステータス')),
                ('order_kubun', models.CharField(max_length=10, verbose_name='注文区分')),
                ('use_kubun', models.CharField(max_length=10, verbose_name='利用区分')),
                ('use_youto', models.CharField(max_length=30, verbose_name='使用用途')),
                ('shukka_annai', models.CharField(max_length=10, verbose_name='出荷案内日')),
                ('nouhin_kigen', models.CharField(max_length=10, verbose_name='納品期限日')),
                ('nouhin_shitei', models.CharField(max_length=10, verbose_name='納品指定日')),
                ('mitsu_day', models.CharField(max_length=10, verbose_name='初回見積日')),
                ('juchu_day', models.CharField(max_length=10, verbose_name='受注日')),
                ('hassou_day', models.CharField(max_length=10, verbose_name='発送完了日')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('sei', models.CharField(max_length=10, verbose_name='姓')),
                ('mei', models.CharField(max_length=10, verbose_name='名')),
                ('mail', models.CharField(max_length=50, verbose_name='メール')),
                ('pref', models.CharField(max_length=10, verbose_name='都道府県')),
                ('com', models.CharField(max_length=50, verbose_name='会社名')),
                ('keiro', models.CharField(max_length=10, verbose_name='流入経路')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
            ],
        ),
    ]
