# Generated by Django 4.2.1 on 2023-07-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='shukka_annai',
        ),
        migrations.AddField(
            model_name='testdata',
            name='kakudo',
            field=models.CharField(default='', max_length=5, verbose_name='確度'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='mitsu_num',
            field=models.CharField(default=1, max_length=10, verbose_name='見積番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdata',
            name='mitsu_id',
            field=models.CharField(max_length=10, verbose_name='見積ID'),
        ),
    ]
