# Generated by Django 3.1.7 on 2023-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0002_remove_testdata_shukka_annai_testdata_kakudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfa_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsu_id', models.CharField(max_length=10, verbose_name='見積ID')),
                ('day', models.CharField(max_length=10, verbose_name='日付')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='testdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
