# Generated by Django 3.1.7 on 2023-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0004_sfa_action_tel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_action',
            name='tel_result',
            field=models.CharField(blank=True, max_length=5, verbose_name='TEL結果'),
        ),
    ]
