# Generated by Django 4.2.1 on 2023-08-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0005_member_busho_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_api',
            field=models.CharField(blank=True, max_length=25, verbose_name='最終API接続'),
        ),
    ]
