# Generated by Django 3.1.7 on 2023-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0005_auto_20230729_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='alert',
            field=models.IntegerField(default=0, verbose_name='アラート'),
        ),
    ]
