# Generated by Django 4.2.1 on 2023-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0008_auto_20230729_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_action',
            name='id',
        ),
        migrations.AddField(
            model_name='sfa_action',
            name='act_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='行動ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sfa_action',
            name='alert_check',
            field=models.IntegerField(default=0, verbose_name='アラート'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
