# Generated by Django 4.2.1 on 2023-08-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0009_remove_sfa_action_id_sfa_action_act_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testdata',
            new_name='Sfa_data',
        ),
    ]
