# Generated by Django 4.2.1 on 2023-08-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0010_rename_testdata_sfa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busho', models.CharField(max_length=15, verbose_name='部署')),
                ('tantou', models.CharField(max_length=10, verbose_name='担当')),
                ('tantou_id', models.CharField(max_length=5, verbose_name='担当ID')),
            ],
        ),
    ]
