# Generated by Django 4.2.1 on 2023-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0011_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='bikou',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
