# Generated by Django 4.2.1 on 2023-10-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0012_alter_sfa_data_com_alter_sfa_data_com_busho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_data',
            name='cus_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客ID'),
        ),
    ]
