# Generated by Django 4.2.1 on 2023-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0012_sfa_data_bikou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_data',
            name='alert',
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='busho_id',
            field=models.CharField(default='', max_length=5, verbose_name='部署ID'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='pay',
            field=models.CharField(default='', max_length=30, verbose_name='支払方法'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='show',
            field=models.IntegerField(default=0, verbose_name='表示'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='tantou_id',
            field=models.CharField(default='', max_length=5, verbose_name='担当ID'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='tel_mob',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='携帯番号'),
        ),
    ]
