# Generated by Django 4.2.1 on 2023-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0013_alter_sfa_data_cus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_action',
            name='cus_id',
            field=models.CharField(default='', max_length=10, verbose_name='顧客ID'),
        ),
    ]
