# Generated by Django 4.2.1 on 2023-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0015_sfa_data_hidden_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='sfa_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsu_id_parent', models.CharField(max_length=10, verbose_name='親ID')),
                ('mitsu_id_child', models.CharField(max_length=10, verbose_name='子ID')),
            ],
        ),
    ]
