# Generated by Django 4.2.1 on 2024-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0017_sfa_data_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='mail_last_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メール最終日'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='nouki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='納期'),
        ),
        migrations.AddField(
            model_name='sfa_data',
            name='tel_last_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TEL最終日'),
        ),
    ]
