# Generated by Django 4.2.1 on 2024-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0018_sfa_data_mail_last_day_sfa_data_nouki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_data',
            name='mitsu_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='見積ID'),
        ),
    ]
