# Generated by Django 4.2.1 on 2024-06-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0020_alter_sfa_data_mitsu_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfa_data_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス')),
                ('s_use_youto', models.CharField(blank=True, max_length=255, null=True, verbose_name='使用用途')),
                ('s_nouki', models.CharField(blank=True, max_length=255, null=True, verbose_name='納期')),
                ('s_make_day', models.CharField(blank=True, max_length=255, verbose_name='見積作成日')),
                ('s_juchu_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='受注日')),
                ('s_hassou_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='発送完了日')),
                ('s_cus_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客氏名')),
                ('s_keiro_tempo', models.IntegerField(default=0, verbose_name='対面あり')),
                ('s_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='TEL最終日_回数')),
                ('s_tel_result', models.IntegerField(default=0, verbose_name='TEL色')),
                ('s_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='メール最終日_回数')),
                ('s_mail_result', models.IntegerField(default=0, verbose_name='メール色')),
                ('s_memo1', models.TextField(blank=True, null=True, verbose_name='コメント表示用')),
                ('s_memo2', models.TextField(blank=True, null=True, verbose_name='コメントポップアップ用')),
                ('s_mitsu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfa.sfa_data')),
            ],
        ),
    ]
