# Generated by Django 4.2.1 on 2024-06-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0022_sfa_data_s_cus_name_sfa_data_s_hassou_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True, verbose_name='発行日')),
                ('tantou', models.CharField(max_length=255, verbose_name='担当')),
                ('meta_data', models.CharField(max_length=255, verbose_name='見積番号')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
