# Generated by Django 4.2.1 on 2025-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0024_alter_credit_url_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='lost_reason',
            field=models.IntegerField(default=0, verbose_name='失注理由'),
        ),
    ]
