# Generated by Django 4.2.1 on 2025-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0026_sfa_data_lost_reason_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_data',
            name='lost_reason_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='その他の失注理由'),
        ),
    ]
