# Generated by Django 4.2.1 on 2025-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0027_alter_sfa_data_lost_reason_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='houjin_col',
            field=models.CharField(default=0, max_length=255, verbose_name='法人カラム'),
        ),
    ]
