# Generated by Django 4.2.1 on 2025-08-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0028_sfa_data_houjin_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='houjin_index',
            field=models.IntegerField(default=0, verbose_name='法人順番'),
        ),
    ]
