# Generated by Django 4.2.1 on 2025-08-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0029_sfa_data_houjin_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='houjin',
            field=models.IntegerField(default=0, verbose_name='法人チーム'),
        ),
    ]
