# Generated by Django 4.2.1 on 2026-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0030_member_houjin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_data',
            name='houjin_col',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='houjin_index',
        ),
    ]
