# Generated by Django 4.2.1 on 2023-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_action',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='行動ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('day', models.CharField(max_length=10, verbose_name='日付')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
                ('alert_check', models.IntegerField(default=0, verbose_name='アラート')),
            ],
        ),
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('com', models.CharField(blank=True, max_length=30, verbose_name='会社名')),
                ('cus_name', models.CharField(blank=True, max_length=20, verbose_name='氏名')),
                ('pref', models.CharField(blank=True, max_length=50, verbose_name='都道府県')),
                ('mitsu_count', models.IntegerField(default=0, verbose_name='見積総数')),
                ('busho_id', models.CharField(blank=True, max_length=10, verbose_name='部署ID')),
                ('tantou_id', models.CharField(blank=True, max_length=10, verbose_name='担当者ID')),
            ],
        ),
    ]
