# Generated by Django 4.2.1 on 2023-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False, verbose_name='行動ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('day', models.CharField(blank=True, max_length=10, verbose_name='行動日')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('detail', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
    ]
