# Generated by Django 4.2.1 on 2023-09-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grip',
            name='com',
        ),
        migrations.RemoveField(
            model_name='grip',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='grip',
            name='mitsu_count',
        ),
        migrations.RemoveField(
            model_name='grip',
            name='pref',
        ),
    ]
