# Generated by Django 4.2.1 on 2023-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='detail',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='action',
            name='day',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
