# Generated by Django 4.2.1 on 2023-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_detail_action_text_alter_action_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='text2',
            field=models.TextField(blank=True, verbose_name='aaa'),
        ),
    ]
