# Generated by Django 4.2.1 on 2023-07-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_action_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='text2',
        ),
    ]
