# Generated by Django 4.2.1 on 2023-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_action_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='day',
            field=models.CharField(max_length=10, verbose_name='日付'),
        ),
    ]
