# Generated by Django 3.1.7 on 2023-07-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_action_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Crm_action',
        ),
    ]
