# Generated by Django 4.2.1 on 2023-10-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_delete_grip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mw_com',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw_mail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='com_busho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部課名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メール'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel_mob',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号'),
        ),
    ]
