# Generated by Django 4.2.1 on 2023-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_action_id_crm_action_act_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('com', models.CharField(blank=True, max_length=30, verbose_name='会社名')),
                ('cus_name', models.CharField(blank=True, max_length=20, verbose_name='氏名')),
                ('pref', models.CharField(blank=True, max_length=50, verbose_name='都道府県')),
                ('mitsu_count', models.IntegerField(default=0, verbose_name='見積総数')),
            ],
        ),
    ]
