# Generated by Django 4.2.1 on 2023-10-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_customer_mw_com_remove_customer_mw_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終コンタクト日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='juchu_all',
            field=models.IntegerField(default=0, verbose_name='受注総数'),
        ),
        migrations.AddField(
            model_name='customer',
            name='juchu_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終受注日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='juchu_money',
            field=models.IntegerField(default=0, verbose_name='受注総金額'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mitsu_all',
            field=models.IntegerField(default=0, verbose_name='見積総数'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mitsu_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積日'),
        ),
    ]
