# Generated by Django 4.2.1 on 2023-08-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_grip'),
    ]

    operations = [
        migrations.AddField(
            model_name='grip',
            name='tantou_id',
            field=models.CharField(default=1, max_length=10, verbose_name='担当者ID'),
            preserve_default=False,
        ),
    ]
