# Generated by Django 4.2.1 on 2023-08-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_grip_tantou_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grip',
            name='tantou_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='担当者ID'),
        ),
    ]
