# Generated by Django 4.2.1 on 2023-10-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_customer_juchu_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客URL'),
        ),
    ]
