# Generated by Django 4.2.1 on 2023-08-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_grip_tantou_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grip',
            name='busho_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='部署ID'),
        ),
    ]
