# Generated by Django 4.2.1 on 2024-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_customer_bikou1_remove_customer_bikou2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='royal',
            field=models.IntegerField(default=0, verbose_name='ロイヤル'),
        ),
    ]
