# Generated by Django 4.2.1 on 2024-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='moeny',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
    ]
