# Generated by Django 4.2.1 on 2024-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_approach_moeny'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='kigen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='期限'),
        ),
    ]
