# Generated by Django 4.2.1 on 2024-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_rename_moeny_approach_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_id', models.IntegerField(verbose_name='アプローチID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('day', models.CharField(max_length=255, verbose_name='日付')),
            ],
        ),
    ]
