# Generated by Django 4.2.1 on 2024-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_approach_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='pref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='approach',
            name='kigen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='版期限'),
        ),
    ]
