# Generated by Django 4.2.1 on 2024-06-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_approach_pref_alter_approach_kigen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='approach_id',
            field=models.IntegerField(max_length=2, verbose_name='アプローチID'),
        ),
    ]
