# Generated by Django 4.2.1 on 2024-06-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_approach_approach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='approach_id',
            field=models.IntegerField(verbose_name='アプローチID'),
        ),
    ]
