# Generated by Django 4.2.1 on 2024-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_approach_approach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='approach_id',
            field=models.CharField(max_length=2, verbose_name='アプローチID'),
        ),
        migrations.AlterField(
            model_name='approach_list',
            name='approach_id',
            field=models.CharField(max_length=2, verbose_name='アプローチID'),
        ),
        migrations.AlterField(
            model_name='crm_action',
            name='approach_id',
            field=models.CharField(default='0', max_length=2, verbose_name='アプローチID'),
        ),
    ]
