# Generated by Django 4.2.1 on 2024-06-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_approach_result_alter_crm_action_approach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mitsu_last_busho_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_部署ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mitsu_last_tantou_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_担当ID'),
        ),
    ]
