# Generated by Django 4.2.1 on 2024-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_customer_mitsu_last_busho_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='taimen',
            field=models.BooleanField(verbose_name='対面'),
        ),
    ]
