# Generated by Django 4.2.1 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_customer_taimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach_list',
            name='action',
            field=models.IntegerField(default=0, verbose_name='行動'),
        ),
    ]
