# Generated by Django 4.2.1 on 2024-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_delete_approach_delete_approach_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id_parent', models.CharField(max_length=10, verbose_name='親ID')),
                ('cus_id_child', models.CharField(max_length=10, verbose_name='子ID')),
            ],
        ),
    ]
