# Generated by Django 4.2.1 on 2024-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_cus_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村'),
        ),
    ]
