# Generated by Django 4.2.1 on 2024-10-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_customer_address_1_customer_address_2_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_tougou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='固定名')),
                ('last_api', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終API接続')),
            ],
        ),
    ]
