# Generated by Django 4.2.1 on 2025-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_cus_tougou'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ran_mw',
            field=models.IntegerField(default=0, verbose_name='ランキングMW'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ran_mw_busho_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ランキングMW_部署ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ran_mw_tantou',
            field=models.CharField(blank=True, max_length=10, verbose_name='ランキングMW_担当名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ran_mw_tantou_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ランキングMW_担当ID'),
        ),
    ]
