# Generated by Django 4.2.1 on 2025-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_customer_ran_mw_customer_ran_mw_busho_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_search_kubun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kubun', models.IntegerField(default=0, verbose_name='区分')),
                ('word', models.CharField(max_length=255, verbose_name='検索単語')),
            ],
        ),
    ]
