# Generated by Django 4.2.1 on 2026-04-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_cus_search_kubun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_ctb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=255, verbose_name='顧客ID')),
                ('cate_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリ_1')),
                ('cate_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリ_2')),
                ('cate_1_ratio', models.FloatField(blank=True, null=True, verbose_name='カテゴリ_1_割合')),
                ('cate_2_ratio', models.FloatField(blank=True, null=True, verbose_name='カテゴリ_2_割合')),
                ('cate_1_hensa', models.IntegerField(blank=True, null=True, verbose_name='カテゴリ_1_偏差値')),
                ('cate_2_hensa', models.IntegerField(blank=True, null=True, verbose_name='カテゴリ_2_偏差値')),
                ('taste_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法_1')),
                ('taste_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法_2')),
                ('taste_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法_3')),
                ('taste_1_ratio', models.FloatField(blank=True, null=True, verbose_name='加工方法_1_割合')),
                ('taste_2_ratio', models.FloatField(blank=True, null=True, verbose_name='加工方法_2_割合')),
                ('taste_3_ratio', models.FloatField(blank=True, null=True, verbose_name='加工方法_3_割合')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='価格帯')),
            ],
        ),
    ]
